[package]
name = "smtp-server"
version = "0.1.1"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7"
clap = "2.33"
trust-dns-resolver = "0.19"
nom = "5.1"
tokio = { version = "0.2", features = ["full"] }
bytes = "0.5"